name: vm-deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

      - name: Get resource group
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Get-AzResourceGroup -Name "riw-demo-actions-rg"
          azPSVersion: "latest"
  
